Repository Deveryware/ansible-haproxy, pull requests merged in 2019-04, with the labels that each got.

#27 Error files are not system-specific anymore
  templates/defaults.cfg
Labels: enhancement

#29 Fix YAML lint errors
  tasks/install/CentOS.yml
  tasks/systemd.yml
  vars/Ubuntu.yml
Labels: bug

#33 Kill two useless conditions
  tasks/configure.yml
Labels: enhancement

#40 Remove epel.repo
  templates/epel.repo
Labels: enhancement

#36 Ensure the stat socket path exists for CentOS
  tasks/install/CentOS.yml
Labels: bug

#38 Update the README
  README.md
Labels: documentation

#39 Multiple x509 certificates
  templates/frontend.cfg
Labels: enhancement

#41 Check if configurable directories exist
  tasks/install.yml
  tasks/install/CentOS.yml
Labels: enhancement
